-- RG-PER-003 / RG-REC-007 : la recherche doit etre insensible a la casse ET
-- aux accents. Les index pg_trgm crees en V1 (idx_personne_nom_trgm,
-- idx_personne_prenoms_trgm) portent sur la colonne brute : une recherche
-- "Kodjo" ne remontait donc pas fiablement une fiche saisie "Kôdjô", le
-- calcul de similarite pg_trgm n'etant pas lui-meme insensible aux accents.
--
-- Ajout additif : extension unaccent uniquement. Deux tentatives
-- precedentes de cette migration essayaient de batir un index fonctionnel
-- GIN trigram sur une expression unaccent(lower(...)) via une fonction
-- wrapper marquee IMMUTABLE (necessaire pour indexer une expression) ; les
-- deux ont echoue au demarrage reel du backend (impossible a tester dans
-- l'environnement de developpement, sans instance PostgreSQL) car
-- PostgreSQL "inline" les fonctions SQL simples utilisees dans un index
-- fonctionnel, et cette optimisation d'inlining bute sur la resolution de
-- type interne de unaccent() dans ce contexte precis (forme a un ou deux
-- arguments, meme resultat) — un probleme documente comme fragile et
-- dependant de la version de PostgreSQL, pas un simple detail de syntaxe.
--
-- Choix retenu, plus simple et robuste : PAS d'index fonctionnel. unaccent()
-- est appele directement dans la requete (PersonneRepository.rechercheApprochee),
-- ce qui est l'usage standard et documente de cette extension et ne souffre
-- d'aucun probleme de resolution de type (contrairement a l'usage dans un
-- index). Cout accepte : la comparaison sur la forme sans accent ne
-- beneficie pas d'un index dedie (sequential scan sur la fonction), donc
-- plus lente qu'un index trigram sur de gros volumes — proportionne pour un
-- projet academique (section 16, anti sur-ingenierie) et les volumes
-- attendus pour le Palier 1. A revisiter si le volume de personnes croit
-- significativement : reintroduire un index fonctionnel en testant
-- explicitement sur l'instance PostgreSQL cible (version precise) plutot
-- qu'a l'aveugle.
--
-- Limite documentee (RG-PER-003 : "a tester explicitement avec des cas reels
-- avant mise en production") : unaccent() traite les diacritiques latins
-- standards (é, è, ê, à, ô, ù, ç...) via decomposition Unicode, mais ne
-- transcrit pas les caracteres propres aux orthographes des langues
-- togolaises (ex. ɖ, ɣ, ŋ, ɔ, ɛ) qui ne sont pas des lettres latines
-- accentuees mais des caracteres distincts. Une table de translitteration
-- dediee, validee avec des locuteurs/donnees reels, reste necessaire avant
-- une mise en production couvrant ces cas — hors de portee d'une correction
-- technique isolee sans validation linguistique.

CREATE EXTENSION IF NOT EXISTS unaccent;
